version: "3.8"

services:
  client:
    build:
      context: ./packages/client/mental-health-tracker-frontend
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-5173}:3000"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:3007}
    depends_on:
      - server

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-3007}:3005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3005
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:

networks:
  default:
    name: mental-health-tracker-network
