name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      DATABASE_URL: postgres://thuppertz:turing_college@localhost:5432/mental_health_tracker_test
      JWT_SECRET: test_secret
      PORT: 3005

    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: thuppertz
          POSTGRES_PASSWORD: turing_college
          POSTGRES_DB: mental_health_tracker_test
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"

      - name: Navigate to server directory
        run: cd packages/server

      - name: Install dependencies
        run: npm ci
        working-directory: packages/server

      - name: Type check
        run: npm run type-check
        working-directory: packages/server

      - name: Lint code
        run: npm run lint
        working-directory: packages/server

      - name: Run database migrations
        run: npm run migrate:latest
        working-directory: packages/server

      - name: Run back-end tests
        run: npm run test
        working-directory: packages/server

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: packages/server/coverage/
          retention-days: 7